# Configuration file for PulseFilter

#logFile: pFilt     # store all pulses, put Null if no output wanted
logFile: Null      # store all pulses, put Null if no output wanted
logFile2: dpFilt   # store double-pulses only, put Null if not wanted
rawFile:  dpRaw    # store raw wave forms, put Null if not wanted
pictFile: dpFigs   # save pictures of double-pulse waveforms

# pulse parameters
#         ______
#        /      \  
#     _ /_ _ _ _ \_ _ _ _ _ _ _   
#                 \__________/
#      r    on  f f2   off  r2 
#                 f2 - r2 for bi-polar only

pulseShape:
# trigger pulse
 - taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9 
   tauf2  : 0. 
   tauoff : 0. 
   taur2  : 0.
   pheight: -0.045
   mode   : 0             # 0:uni-polar  1: bipolar 

# other pulses
 - taur   : 20.E-9
   tauon  : 12.E-9 
   tauf   : 128.E-9 
   tauf2  : 0. 
   tauoff : 0. 
   taur2  : 0.
   pheight: -0.035
   mode   : 0             # 0:uni-polar  1: bipolar 

modules: [RMeter, Display, Hists]

histograms:
 - [0., 0.4, 50, 20., "noise Trg. Pulse (V)", 0]
  # min max Nbins ymax    title              lin/log
 - [0., 0.8, 50, 15., "valid Trg. Pulse (V)", 0]
 - [0., 15.,  45, 7.5, "Tau (µs)", 1]
# - [0., 0.8, 50, 15., "Pulse Height (V)", 0]

doublePulse: True  # switch to control double-pulse search

